# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a49aa0521203dda464a3fc8f6efb23fb1ae7185e7de717e460f7dc7f47516a45a8f2b490cb6bff7f22a024d2caa6f01db1d9c425abfdfedac03ba87b53744778

test:
  secret_key_base: a00d93364c820139c2f57666b0b6c2dc262e22540e8df0ade3168000c2eda24bde6ec1dca9a6f5289c97c91b0ae52f3b149c6444ed9542a3fe4c476f3ceb95d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
